
// 购物车数量增减
export const SHOPCART_INCREMENT = 'SHOPCART_INCREMENT'
export type SHOPCART_INCREMENT = typeof SHOPCART_INCREMENT
export const SHOPCART_DECREMENT = 'SHOPCART_DECREMENT'
export type SHOPCART_DECREMENT = typeof SHOPCART_DECREMENT
